categories:
  - title: '🚀 Enhancements'
    labels:
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bugfix'
  - title: '🌎 Localization'
    labels:
      - 'localization'
  - title: '🧰 Maintenance'
    label:
      - 'chore'
      - 'documentation'
      - 'dependencies'
template: |
  Install Rhodon using one of the methods listed [here](https://github.com/mpwg/Rhodon#installation).
  Update Rhodon by selecting Check for Updates... in the Rhodon menu in the menu bar.

  ## Changes

  $CHANGES
